import {topology as t} from '../experiments/cube-topology/topology.mjs';
import {createPlayer,leftClickState,rightClickState} from './player.mjs';
import {makeVariants} from './variants.mjs';
import {createRenderer} from './renderer3d.mjs';
const $=id=>document.getElementById(id), labels='ROYGBIV', names=['Red','Orange','Yellow','Green','Blue','Indigo','Violet'];
try {
  const response=await fetch('/experiments/rainbow-cube/examples.json'); if(!response.ok)throw Error('Could not load fixtures');
  const variants=makeVariants(await response.json()), selector=$('variant'), buttons=[]; Object.keys(variants).forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=id==='D'?'D (debug / ambiguous)':id;selector.append(o);});
  let board=variants.C0, player=createPlayer(board.maps,t,board.fixed), revision=0, worker=null, timer,renderer;
  function setupRenderer(){renderer?.dispose?.();renderer=createRenderer($('cube'),{topology:t,maps:board.maps,player,diagnostic:new URLSearchParams(location.search).has('geometry-diagnostic'),onInput:d=>{$('input-debug').textContent=d.text;},onPick:(id,button)=>{if(!player.fixed.has(id)){const state=player.get(id),next=button===2?rightClickState(state):leftClickState(state);player.set(id,next);render();}},onHover:id=>{if(id)info(id);},onError:error=>{$('status').textContent=error;$('status').className='error';}});}
  function setBoard(id){board=variants[id];player=createPlayer(board.maps,t,board.fixed);buttons.length=0;$('net').replaceChildren();renderBoard();setupRenderer();revision++;render();}
  function renderBoard(){for(const face of t.faces){const section=document.createElement('section');section.className='face';section.style.setProperty('--face',face);const h=document.createElement('h2');h.textContent=face;const grid=document.createElement('div');grid.className='grid';section.append(h,grid);$('net').append(section);
    for(let row=0;row<7;row++)for(let col=0;col<7;col++){const id=t.faceCellToPhysical(face,row,col),region=board.maps[face][row*7+col],b=document.createElement('button');b.type='button';b.className='cell';b.dataset.physical=id;b.dataset.description=`${face}, row ${row+1}, column ${col+1}, ${names[region]} region`;b.style.setProperty('--color',`var(--${labels[region]})`);b.style.setProperty('--ink',region===5?'white':'#181820');b.classList.toggle('fixed',player.fixed.has(id));b.classList.toggle('region-right',col===6||board.maps[face][row*7+col+1]!==region);b.classList.toggle('region-bottom',row===6||board.maps[face][(row+1)*7+col]!==region);b.addEventListener('click',()=>{if(!player.fixed.has(id)){player.cycle(id);render();}info(id);});b.addEventListener('pointerenter',()=>info(id));b.addEventListener('focus',()=>info(id));buttons.push(b);grid.append(b);}
  }}
  function info(id){$('cell-info').textContent=t.physicalToFaceCells(id).map(r=>`${r.face} r${r.row+1}c${r.col+1}`).join(' ↔ ');buttons.forEach(b=>b.classList.toggle('linked',b.dataset.physical===id));}
  function requestCount(){clearTimeout(timer);if(!$('developer').open)return;$('compatible').textContent='Calculating…';const current=revision;timer=setTimeout(()=>{if(!worker){worker=new Worker(new URL('./solver-worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(data.revision!==revision)return;$('compatible').textContent=data.error?'Unavailable':data.exact?data.count:`At least ${data.count}`;};}worker.postMessage({revision:current,maps:board.maps,marks:player.marks()});},80);}
  function render(){const e=player.evaluate(),bad=new Set(e.contradictions.flatMap(c=>c.involved));buttons.forEach(b=>{const id=b.dataset.physical,s=player.get(id);b.textContent=player.fixed.has(id)?'◆':['','×','★'][s];b.dataset.state=player.fixed.has(id)?'fixed':['unknown','excluded','unicorn'][s];b.classList.toggle('fixed',player.fixed.has(id));b.classList.toggle('conflict',bad.has(id));b.setAttribute('aria-label',`${b.dataset.description}: ${b.dataset.state}`);});$('undo').disabled=!player.canUndo;$('reset').disabled=buttons.every(b=>player.fixed.has(b.dataset.physical)||player.get(b.dataset.physical)===0);$('status').textContent=e.solved?'Solved!':e.contradictions.length?`${e.contradictions.length} contradiction(s).`:'No rule contradictions detected.';$('status').className=e.solved?'solved':e.contradictions.length?'error':'';$('contradictions').replaceChildren(...e.contradictions.map(c=>{const li=document.createElement('li');li.textContent=`${c.face}: ${c.kind} ${c.kind==='region'?labels[c.index]:c.index+1} — ${c.reason}.`;return li;}));$('selected').textContent=board.id;$('fixed-count').textContent=board.fixed.length;$('placed').textContent=[...player.marks().required].filter(id=>!player.fixed.has(id)).length;$('dev-conflict').textContent=e.contradictions.length?'Yes':'No';revision++;requestCount();}
  function view(mode){$('cube-wrap').style.display=mode==='3d'?'block':'none';$('net-scroll').style.display=mode==='2d'?'block':'none';$('view-3d').classList.toggle('view-active',mode==='3d');$('view-2d').classList.toggle('view-active',mode==='2d');$('view-3d').setAttribute('aria-pressed',mode==='3d');$('view-2d').setAttribute('aria-pressed',mode==='2d');}
  names.forEach((name,i)=>{const span=document.createElement('span');span.className='swatch';span.style.setProperty('--color',`var(--${labels[i]})`);span.textContent=`${labels[i]} · ${name}`;$('legend').append(span);});
  selector.value='C0';selector.onchange=()=>setBoard(selector.value);$('view-3d').onclick=()=>view('3d');$('view-2d').onclick=()=>view('2d');$('undo').onclick=()=>{player.undo();render();};$('reset').onclick=()=>{player.reset();render();};$('developer').addEventListener('toggle',requestCount);$('show-solution').onclick=()=>{player.showSolution(board.truth);render();};$('show-solution').disabled=false;renderBoard();setupRenderer();view('3d');render();
}catch(error){$('status').textContent=`Unable to start: ${error.message}`;$('status').className='error';}
