import {topology as defaultTopology} from '../experiments/cube-topology/topology.mjs';
import {UNKNOWN,EXCLUDED,UNICORN} from './player.mjs';

const palette=[[.82,.25,.38],[.9,.48,.18],[.92,.78,.28],[.3,.65,.48],[.25,.55,.82],[.32,.28,.58],[.68,.42,.72]];
const sub=(a,b)=>a.map((x,i)=>x-b[i]), add=(a,b)=>a.map((x,i)=>x+b[i]), mul=(a,s)=>a.map(x=>x*s);
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const neg=a=>a.map(x=>-x);
// Render frames share the verified logical orientation: U follows columns,
// V points toward the visual top (opposite the logical row direction), and N
// is the outward normal. Geometry never depends on canonical cell coordinates.
export function makeRenderFrames(topology){
  return Object.fromEntries(topology.faces.map(face=>{const f=topology.frames[face];return [face,{center:f.normal.slice(),u:f.column.slice(),v:neg(f.row),normal:f.normal.slice()}];}));
}
export function faceQuad(frame,row,col,n=7,offset=0){const s=2/n,u0=-1+col*s,u1=u0+s,v1=1-row*s,v0=v1-s,center=add(frame.center,mul(frame.normal,offset)),p=(u,v)=>add(add(center,mul(frame.u,u)),mul(frame.v,v));return [p(u0,v0),p(u1,v0),p(u1,v1),p(u0,v1)];}
function identity(){return [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];}
function multiply(a,b){const o=Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function perspective(fovy,aspect,near,far){const f=1/Math.tan(fovy/2),q=1/(near-far);return [f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*q,-1,0,0,2*far*near*q,0];}
function rotation(x,y){const cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y);return [cy,0,-sy,0,sx*sy,cx,sx*cy,0,cx*sy,-sx,cx*cy,0,0,0,0,1];}
function transform(m,p){return [m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14],m[3]*p[0]+m[7]*p[1]+m[11]*p[2]+m[15]];}
function inverse(a){const b00=a[0]*a[5]-a[1]*a[4],b01=a[0]*a[6]-a[2]*a[4],b02=a[0]*a[7]-a[3]*a[4],b03=a[1]*a[6]-a[2]*a[5],b04=a[1]*a[7]-a[3]*a[5],b05=a[2]*a[7]-a[3]*a[6],b06=a[8]*a[13]-a[9]*a[12],b07=a[8]*a[14]-a[10]*a[12],b08=a[8]*a[15]-a[11]*a[12],b09=a[9]*a[14]-a[10]*a[13],b10=a[9]*a[15]-a[11]*a[13],b11=a[10]*a[15]-a[11]*a[14],det=b00*b11-b01*b10+b02*b09+b03*b08-b04*b07+b05*b06;if(!det)return null;const d=1/det;return [(a[5]*b11-a[6]*b10+a[7]*b09)*d,(-a[1]*b11+a[2]*b10-a[3]*b09)*d,(a[13]*b05-a[14]*b04+a[15]*b03)*d,(-a[9]*b05+a[10]*b04-a[11]*b03)*d,(-a[4]*b11+a[6]*b08-a[7]*b07)*d,(a[0]*b11-a[2]*b08+a[3]*b07)*d,(-a[12]*b05+a[14]*b02-a[15]*b01)*d,(a[8]*b05-a[10]*b02+a[11]*b01)*d,(a[4]*b10-a[5]*b08+a[7]*b06)*d,(-a[0]*b10+a[1]*b08-a[3]*b06)*d,(a[12]*b04-a[13]*b02+a[15]*b00)*d,(-a[8]*b04+a[9]*b02-a[11]*b00)*d,(-a[4]*b09+a[5]*b07-a[6]*b06)*d,(a[0]*b09-a[1]*b07+a[2]*b06)*d,(-a[12]*b03+a[13]*b01-a[14]*b00)*d,(a[8]*b03-a[9]*b01+a[10]*b00)*d];}
export function toNdc(rect,x,y){return [(x-rect.left)/rect.width*2-1,1-(y-rect.top)/rect.height*2];}
export const classifyGesture=distance=>distance<=5?'click':'drag';

export function createRenderer(canvas,{topology=defaultTopology,maps,player,onPick,onHover,onInput,onError,diagnostic=false}={}){
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL is unavailable');
  const vs=`attribute vec3 p;uniform mat4 mvp;void main(){gl_Position=mvp*vec4(p,1.0);}`;
  const fs=`precision mediump float;uniform vec3 color;void main(){gl_FragColor=vec4(color,1.0);}`;
  const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
  const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(`WebGL link failed: ${gl.getProgramInfoLog(program)}`);
  const pos=gl.getAttribLocation(program,'p'),mvp=gl.getUniformLocation(program,'mvp'),color=gl.getUniformLocation(program,'color');if(pos<0||!mvp||!color)throw Error(`WebGL locations missing (attribute p=${pos}, mvp=${Boolean(mvp)}, color=${Boolean(color)})`);
  const buffer=gl.createBuffer();if(!buffer)throw Error('WebGL buffer creation failed');const initError=gl.getError();if(initError!==gl.NO_ERROR)throw Error(`WebGL initialization error 0x${initError.toString(16)}`);let rx=-.34,ry=.55,drag=null,hover=null,reportedError=false;
  const frames=makeRenderFrames(topology),epsilon=.001;
  function cellQuad(face,row,col,layer=0){return faceQuad(frames[face],row,col,7,epsilon*layer);}
  function draw(vertices,rgba,mode=gl.TRIANGLES,matrix){if(!vertices.length)return;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.DYNAMIC_DRAW);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(pos);gl.uniformMatrix4fv(mvp,false,matrix);gl.uniform3fv(color,rgba);gl.drawArrays(mode,0,vertices.length/3);}
  function resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,canvas.clientWidth*d),h=Math.max(1,canvas.clientHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);}
  function viewMatrix(){const view=identity();view[14]=-5;return view;}
  function render(){resize();gl.useProgram(program);gl.disable(gl.CULL_FACE);gl.enable(gl.DEPTH_TEST);gl.clearColor(.018,.022,.04,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const proj=perspective(Math.PI/4,canvas.width/canvas.height,.1,100),mv=multiply(viewMatrix(),rotation(rx,ry));const matrix=multiply(proj,mv),diagnosticPalette=[[.9,.25,.3],[.95,.55,.18],[.9,.85,.2],[.25,.7,.4],[.2,.55,.9],[.4,.3,.75]];for(const [faceIndex,face] of topology.faces.entries())for(let r=0;r<7;r++)for(let c=0;c<7;c++){const q=cellQuad(face,r,c),region=maps[face][r*7+c],verts=[...q[0],...q[1],...q[2],...q[0],...q[2],...q[3]];draw(verts,diagnostic?diagnosticPalette[faceIndex]:palette[region],gl.TRIANGLES,matrix);}
    if(!diagnostic){const glyph=[],excluded=[];for(const cell of topology.physicalCells){const state=player.get(cell.id);if(state===UNKNOWN)continue;for(const ref of cell.faceCells){const q=cellQuad(ref.face,ref.row,ref.col,3),center=q.reduce((a,p)=>add(a,p),[0,0,0]).map(x=>x/4),f=frames[ref.face],u=mul(f.u,.055),v=mul(f.v,.055),p=center;if(state===UNICORN){glyph.push(...add(add(p,mul(u,-1)),[0,0,0]),...add(add(p,mul(v,-1)),u),...add(add(p,u),[0,0,0]),...add(add(p,mul(u,-1)),v),...add(add(p,mul(v,-1)),[0,0,0]),...add(add(p,mul(u,-1)),v),...add(add(p,u),[0,0,0]),...add(add(p,mul(v,-1)),u));}else{excluded.push(...add(add(p,mul(u,-1)),mul(v,-1)),...add(add(p,u),v),...add(add(p,u),mul(v,-1)),...add(add(p,mul(u,-1)),v));}}}draw(glyph,[.96,.98,1],gl.TRIANGLES,matrix);draw(excluded,[.25,.27,.34],gl.LINES,matrix);if(hover) {for(const ref of topology.physicalToFaceCells(hover)){const q=cellQuad(ref.face,ref.row,ref.col,2),vtx=[...q[0],...q[1],...q[1],...q[2],...q[2],...q[3],...q[3],...q[0]];draw(vtx,[1,.92,.48],gl.LINES,matrix);}}}const frameError=gl.getError();if(frameError!==gl.NO_ERROR&&!reportedError){reportedError=true;onError?.(`WebGL frame error 0x${frameError.toString(16)}`);return;}requestAnimationFrame(render);}
  function pick(x,y){const ndc=toNdc(canvas.getBoundingClientRect(),x,y),proj=perspective(Math.PI/4,canvas.width/canvas.height,.1,100),m=inverse(multiply(proj,multiply(viewMatrix(),rotation(rx,ry))));if(!m)return null;const a=transform(m,[ndc[0],ndc[1],-1,1]),b=transform(m,[ndc[0],ndc[1],1,1]);const ro=a.slice(0,3).map((v,i)=>v/a[3]),rd=sub(b.slice(0,3).map((v,i)=>v/b[3]),ro);let best=null,bestD=Infinity;for(const face of topology.faces){const f=frames[face],den=dot(rd,f.normal);if(Math.abs(den)<1e-6)continue;const d=dot(sub(f.center,ro),f.normal)/den;if(d<=0||d>=bestD)continue;const hit=add(ro,mul(rd,d)),u=dot(sub(hit,f.center),f.u),v=dot(sub(hit,f.center),f.v);if(u<-1||u>1||v<-1||v>1)continue;const col=Math.min(6,Math.max(0,Math.floor((u+1)*3.5))),row=Math.min(6,Math.max(0,Math.floor((1-v)*3.5)));best=topology.faceCellToPhysical(face,row,col);bestD=d;}return best;}
  const stateName=s=>['blank','excluded','unicorn'][s]||'unknown';
  canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,rx,ry,moved:false,button:e.button};onInput?.({text:`input: ${e.button===2?'right':'left'} pointerdown`});});canvas.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;ry=drag.ry+dx*.008;rx=Math.max(-1.35,Math.min(1.35,drag.rx+dy*.008));}const id=pick(e.clientX,e.clientY);if(id!==hover){hover=id;onHover?.(id);}});canvas.addEventListener('pointerup',e=>{if(!drag)return;const d=Math.hypot(e.clientX-drag.x,e.clientY-drag.y),click=classifyGesture(d)==='click',id=click?pick(e.clientX,e.clientY):null;if(click&&id){const reps=topology.physicalToFaceCells(id),r=reps[0],before=player.get(id);onPick?.(id,drag.button);onInput?.({text:`input: ${drag.button===2?'right':'left'} click · movement: ${d.toFixed(1)}px · pick: ${r.face} r${r.row+1}c${r.col+1} · physical: ${id} · state: ${stateName(before)} → ${stateName(player.get(id))}`});}else onInput?.({text:`input: ${drag.button===2?'right':'left'} ${click?'click':'drag'} · movement: ${d.toFixed(1)}px · pick: ${id||'NONE'}`});drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);render();return {pick,render,get rotation(){return {x:rx,y:ry};},set rotation(v){rx=v.x;ry=v.y;}};
}
